CREATE TABLE [dbo].[ARLINH_local]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[DocumentNumber] [nvarchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LocationKey] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerKey] [nvarchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ItemKey] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ItemDescription] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UnitPrice] [float] NULL,
[QtyOrdered] [float] NULL,
[QtyShipped] [float] NULL,
[TaxKey] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RevenueAcctKey] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CostAmt] [float] NULL,
[CustomerClassKey] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RequestDate] [datetime] NULL,
[ShipDate] [datetime] NULL,
[DocumentDate] [datetime] NULL,
[DiscountPercent] [float] NULL,
[ActualTaxLevel1Amt] [float] NULL,
[ActualTaxLevel2Amt] [float] NULL,
[ActualTaxLevel3Amt] [float] NULL,
[ActualTaxLevel4Amt] [float] NULL,
[OrderInfo] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BolInfo] [nvarchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SysDocID] [int] NULL,
[SysLinSq] [smallint] NULL,
[OrigSysID] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OrigDocID] [int] NULL,
[OrigLinSq] [smallint] NULL,
[RefSysID] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RefDocID] [int] NULL,
[RefLinSq] [smallint] NULL,
[RefType] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShipDocID] [int] NULL,
[RsrvNC] [nvarchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LineItemType] [nvarchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TransactionType] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reference] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BOLNum] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CrefItemNum] [nvarchar] (39) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InvPostByShip] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustPONo] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SellingUOM] [nvarchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SellQtyOrdered] [float] NULL,
[ShipQuantity] [float] NULL,
[SellUnitPrice] [float] NULL,
[SellUOMMultiplie] [float] NULL,
[SellUOMKey] [nvarchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Spare] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Spare2] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Spare3] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RecUserID] [nvarchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RecDate] [datetime] NULL,
[RecTime] [nvarchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[User01] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[User02] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[User03] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[User04] [datetime] NULL,
[User05] [datetime] NULL,
[User06] [datetime] NULL,
[User07] [int] NULL,
[User08] [int] NULL,
[User09] [int] NULL,
[DateModified] [datetime] NULL CONSTRAINT [df_ARLINH_DateModified] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ARLINH_local] ADD CONSTRAINT [PK_ARLINH_local] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_ARLINH_DocumentDate_CustomerClassKey] ON [dbo].[ARLINH_local] ([DocumentDate], [CustomerClassKey]) INCLUDE ([ActualTaxLevel1Amt], [ActualTaxLevel2Amt], [ActualTaxLevel3Amt], [ActualTaxLevel4Amt], [BolInfo], [BOLNum], [CostAmt], [CrefItemNum], [CustomerKey], [CustPONo], [DateModified], [DiscountPercent], [DocumentNumber], [ID], [InvPostByShip], [ItemDescription], [ItemKey], [LineItemType], [LocationKey], [OrderInfo], [OrigDocID], [OrigLinSq], [OrigSysID], [QtyOrdered], [QtyShipped], [RecDate], [RecTime], [RecUserID], [RefDocID], [Reference], [RefLinSq], [RefSysID], [RefType], [RequestDate], [RevenueAcctKey], [RsrvNC], [SellingUOM], [SellQtyOrdered], [SellUnitPrice], [SellUOMKey], [SellUOMMultiplie], [ShipDate], [ShipDocID], [ShipQuantity], [Spare], [Spare2], [Spare3], [SysDocID], [SysLinSq], [TaxKey], [TransactionType], [UnitPrice], [User01], [User02], [User03], [User04], [User05], [User06], [User07], [User08], [User09]) ON [PRIMARY]
GO
EXEC sp_addextendedproperty N'MS_Description', 'Accounts receivable line item transactions.', 'SCHEMA', N'dbo', 'TABLE', N'ARLINH_local', NULL, NULL
GO
