CREATE TABLE [dbo].[tblSubscr_Audit]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[ID_FK] [int] NULL,
[SubSSN] [nvarchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SubID] [nvarchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SubStatus] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SubGroupID] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PltCustKey] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlanID] [int] NULL,
[CoverID] [int] NULL,
[RateID] [int] NULL,
[SubCancelled] [int] NULL,
[SubLastName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SubFirstName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SubMiddleName] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SubStreet1] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SubStreet2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SubCity] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SubState] [nvarchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SubZip] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SubPhoneWork] [nvarchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SubPhoneHome] [nvarchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SubEmail] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SubDOB] [datetime] NULL,
[DateModified] [datetime] NULL,
[EIMBRID] [nvarchar] (13) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sub_LUName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DepCnt] [int] NULL,
[SubGender] [nvarchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SubAge] [int] NULL,
[SubMaritalStatus] [nvarchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SubEffDate] [datetime] NULL,
[SubExpDate] [datetime] NULL,
[SubClassKey] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PreexistingDate] [datetime] NULL,
[SubCardPrt] [bit] NULL,
[SubCardPrtDte] [datetime] NULL,
[SubNotes] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TransactionType] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SubContBeg] [datetime] NULL,
[SubContEnd] [datetime] NULL,
[SubPymtFreq] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SubGeoID] [nvarchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SubBankDraftNo] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Flag] [bit] NULL,
[UserName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateCreated] [datetime] NULL,
[DateUpdated] [datetime] NULL,
[DateDeleted] [datetime] NULL,
[SubFlyerPrtDte] [datetime] NULL,
[SubRate] [float] NULL,
[SubCOBRA] [bit] NULL,
[SubLOA] [bit] NULL,
[SubMissing] [bit] NULL,
[CreateDate] [datetime] NULL,
[ModifyDate] [datetime] NULL,
[AmtPaid] [money] NULL,
[wSubID] [int] NULL,
[User01] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[User02] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[User03] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[User04] [datetime] NULL,
[User05] [datetime] NULL,
[User06] [datetime] NULL,
[User07] [int] NULL,
[User08] [int] NULL,
[User09] [int] NULL,
[Email] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GUID] [uniqueidentifier] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[tblSubscr_Audit] ADD CONSTRAINT [PK_tblSubscr_Audit] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
EXEC sp_addextendedproperty N'MS_Description', 'Tracking table for adds/changes/deletes to tblSubscr.', 'SCHEMA', N'dbo', 'TABLE', N'tblSubscr_Audit', NULL, NULL
GO
