CREATE TABLE [dbo].[ARTRANH_temp]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[DocumentNumber] [nvarchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ApplyTo] [nvarchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TerritoryKey] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SalespersonKey] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerKey] [nvarchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerClassKey] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OrderNumber] [nvarchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShipToKey] [nvarchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CheckBatch] [nvarchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TransactionType] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DocumentDate] [datetime] NULL,
[AgeDate] [datetime] NULL,
[DaysTillDue] [smallint] NULL,
[DocumentAmt] [float] NULL,
[DiscountAmt] [float] NULL,
[FreightAmt] [float] NULL,
[TaxAmt] [float] NULL,
[CostAmt] [float] NULL,
[CommissionHomeOvride] [float] NULL,
[RetentionInvoice] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SysDocID] [int] NOT NULL,
[ApplySysDocID] [int] NULL,
[Spare] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Spare2] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Spare3] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RecUserID] [nvarchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RecDate] [datetime] NULL,
[RecTime] [nvarchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[User01] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[User02] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[User03] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[User04] [datetime] NULL,
[User05] [datetime] NULL,
[User06] [datetime] NULL,
[User07] [int] NULL,
[User08] [int] NULL,
[User09] [int] NULL,
[DateModified] [datetime] NULL,
[IFStatus] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
