CREATE TABLE [dbo].[tblEDI_App_Subscr]
(
[SubSSN] [nvarchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SubID] [nvarchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EIMBRID] [nvarchar] (13) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SubStatus] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SubGroupID] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PltCustKey] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlanID] [int] NULL,
[CoverID] [int] NULL,
[RateID] [int] NULL,
[SubCancelled] [int] NULL,
[SUB_LUname] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SubLastName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SubFirstName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SubMiddleName] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SubStreet1] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SubStreet2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SubCity] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SubState] [nvarchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SubZip] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SubPhoneWork] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SubPhoneHome] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SUBdob] [datetime] NULL,
[DepCnt] [int] NULL,
[SubGender] [nvarchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SubAge] [int] NULL,
[SubMaritalStatus] [nvarchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SubEffDate] [datetime] NULL,
[SubExpDate] [datetime] NULL,
[SubClassKey] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PreexistingDate] [datetime] NULL,
[SubCardPrt] [bit] NULL CONSTRAINT [DF_tblEDI_App_Subscr_SubCardPrt] DEFAULT ((0)),
[SubCardPrtDte] [datetime] NULL,
[SubNotes] [ntext] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TransactionType] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SubContBeg] [datetime] NULL,
[SubContEnd] [datetime] NULL,
[SubPymtFreq] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SubGeoID] [nvarchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SUBbankDraftNo] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Flag] [bit] NULL CONSTRAINT [DF_tblEDI_App_Subscr_Flag] DEFAULT ((0)),
[UserName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateCreated] [datetime] NULL,
[DateUpdated] [datetime] NULL,
[DateDeleted] [datetime] NULL,
[SubEmail] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SUBflyerPRTdte] [datetime] NULL,
[SUBrate] [float] NULL,
[SUBCOBRA] [bit] NULL CONSTRAINT [DF_tblEDI_App_Subscr_SUBCOBRA] DEFAULT ((0)),
[SUBLOA] [bit] NULL CONSTRAINT [DF_tblEDI_App_Subscr_SUBLOA] DEFAULT ((0)),
[SUBmissing] [bit] NULL CONSTRAINT [DF_tblEDI_App_Subscr_SUBmissing] DEFAULT ((0)),
[CreateDate] [datetime] NULL CONSTRAINT [DF_tblEDI_App_Subscr_CreateDate] DEFAULT (getdate()),
[ModifyDate] [datetime] NULL,
[wSubID] [int] NULL,
[wUpt] [int] NULL,
[AmtPaid] [money] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[tblEDI_App_Subscr] ADD CONSTRAINT [PK_tblEDI_App_Subscr] PRIMARY KEY CLUSTERED  ([SubSSN]) ON [PRIMARY]
GO
EXEC sp_addextendedproperty N'MS_Description', 'Temp table used to process subscriber EDI data.', 'SCHEMA', N'dbo', 'TABLE', N'tblEDI_App_Subscr', NULL, NULL
GO
